server:
  port: 9000
  forward-headers-strategy: framework

spring:
  config:
    import: optional:file:./.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: OneBitArticle
      auto-index-creation: false

  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.mongo.MongoHealthContributorAutoConfiguration

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS}
  refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS}

ai:
  server:
    url: ${AI_SERVER_URL:http://localhost:8000}
  internal-key: ${AI_INTERNAL_KEY:}

cors:
  allowed-origins: "http://localhost:3000, http://192.168.219.101:8081, https://onebitearticle.com, http://onebitearticle.com, http://localhost:8081"
